// <auto-generated />
using System;
using Game106.Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game106.Backend.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260328011720_RemoveUnusedPlayersTable")]
    partial class RemoveUnusedPlayersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game106.Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinkAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49f846e7-d9d0-4330-8be8-1d068535ba38",
                            Email = "user1@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LinkAvatar = "https://cdn-icons-png.flaticon.com/512/149/149071.png",
                            LockoutEnabled = false,
                            Name = "Người chơi số 1",
                            NormalizedEmail = "USER1@GMAIL.COM",
                            NormalizedUserName = "USER1",
                            OTP = "",
                            PasswordHash = "AQAAAAIAAYagAAAAEElkUF1TQ3LLwcjkwOCYj+BQGTE1fWNxphkeSerOw/Uu8PW+9mL87sMI7ChsXa+yxg==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            RoleId = 2,
                            SecurityStamp = "19037974-6202-4a8f-b134-cca8f6f742f9",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ab08a48-51a8-452b-9b5f-7d2b60d4f0bd",
                            Email = "user2@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LinkAvatar = "https://cdn-icons-png.flaticon.com/512/149/149071.png",
                            LockoutEnabled = false,
                            Name = "Người chơi số 2",
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "USER2",
                            OTP = "",
                            PasswordHash = "AQAAAAIAAYagAAAAEGU2AziBn+d6Uqby0vg8VNS4eoyhtNTjF74TL8VyoROo+SyLASEDXYJBS20gtGm58A==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            RoleId = 2,
                            SecurityStamp = "785c98f6-fe04-48c3-9606-e13ef6fa6085",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a90055b4-23c6-4c44-a09f-2d78badf884b",
                            Email = "user3@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LinkAvatar = "https://cdn-icons-png.flaticon.com/512/149/149071.png",
                            LockoutEnabled = false,
                            Name = "Người chơi số 3",
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "USER3",
                            OTP = "",
                            PasswordHash = "AQAAAAIAAYagAAAAEJgxwmGF4oVSQwNl9pDXwPyIbCP/GVDbFoPgkAHHz/6zN+qc3RqqlcMj/Cc4W2uAsQ==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            RoleId = 2,
                            SecurityStamp = "61e06fbf-1c26-44a0-bcfb-936f319141b6",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "17f6460d-652a-4e8a-a8ae-de92e6c8c607",
                            Email = "user4@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LinkAvatar = "https://cdn-icons-png.flaticon.com/512/149/149071.png",
                            LockoutEnabled = false,
                            Name = "Người chơi số 4",
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "USER4",
                            OTP = "",
                            PasswordHash = "AQAAAAIAAYagAAAAENfodsIkokg707sqn2l3bAHZDwBW9mqD99D9MSH068ZqIom3tC7nieZBSyhs9bAz5g==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            RoleId = 2,
                            SecurityStamp = "d7603683-c8ea-46a4-8aed-cf74f123b4ed",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dd48135-cd68-41ed-9938-1a281115b55c",
                            Email = "user5@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LinkAvatar = "https://cdn-icons-png.flaticon.com/512/149/149071.png",
                            LockoutEnabled = false,
                            Name = "Người chơi số 5",
                            NormalizedEmail = "USER5@GMAIL.COM",
                            NormalizedUserName = "USER5",
                            OTP = "",
                            PasswordHash = "AQAAAAIAAYagAAAAELXBUumnyS30KWq2ipfyWt3v58r2dm/CERdmJT9XxkXCKKH2VDWAe1lgJrfg7j0SAQ==",
                            PhoneNumberConfirmed = false,
                            RegionId = 1,
                            RoleId = 2,
                            SecurityStamp = "f975947b-e5e3-4712-8337-e510d8a31a3f",
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        });
                });

            modelBuilder.Entity("Game106.Backend.Models.GameLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelId");

                    b.ToTable("GameLevels");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            Description = "Câu hỏi cơ bản cho người mới bắt đầu",
                            Title = "Dễ"
                        },
                        new
                        {
                            LevelId = 2,
                            Description = "Câu hỏi mức độ trung bình",
                            Title = "Trung bình"
                        },
                        new
                        {
                            LevelId = 3,
                            Description = "Câu hỏi thử thách dành cho chuyên gia",
                            Title = "Khó"
                        });
                });

            modelBuilder.Entity("Game106.Backend.Models.GameRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("GameRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Player"
                        });
                });

            modelBuilder.Entity("Game106.Backend.Models.LevelResult", b =>
                {
                    b.Property<int>("QuizResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizResultId"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuizResultId");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("LevelResults");
                });

            modelBuilder.Entity("Game106.Backend.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("LevelId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "4",
                            ContentQuestion = "2 + 2 = ?",
                            LevelId = 1,
                            Option1 = "3",
                            Option2 = "4",
                            Option3 = "5",
                            Option4 = "6"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "Hà Nội",
                            ContentQuestion = "Thủ đô của Việt Nam là gì?",
                            LevelId = 1,
                            Option1 = "Hà Nội",
                            Option2 = "TP.HCM",
                            Option3 = "Đà Nẵng",
                            Option4 = "Huế"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "C#",
                            ContentQuestion = "Ngôn ngữ lập trình nào tạo ra .NET?",
                            LevelId = 2,
                            Option1 = "Java",
                            Option2 = "Python",
                            Option3 = "C#",
                            Option4 = "Go"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "Not Found",
                            ContentQuestion = "HTTP status 404 có nghĩa là gì?",
                            LevelId = 2,
                            Option1 = "OK",
                            Option2 = "Not Found",
                            Option3 = "Server Error",
                            Option4 = "Unauthorized"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "Inversion of Control",
                            ContentQuestion = "Design pattern nào dùng trong Dependency Injection?",
                            LevelId = 3,
                            Option1 = "Singleton",
                            Option2 = "Factory",
                            Option3 = "Inversion of Control",
                            Option4 = "Observer"
                        });
                });

            modelBuilder.Entity("Game106.Backend.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Miền Bắc"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Miền Trung"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "Miền Nam"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Game106.Backend.Models.LevelResult", b =>
                {
                    b.HasOne("Game106.Backend.Models.GameLevel", "GameLevel")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game106.Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Game106.Backend.Models.Question", b =>
                {
                    b.HasOne("Game106.Backend.Models.GameLevel", "GameLevel")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Game106.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Game106.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game106.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Game106.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
